### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by wilsonmar** [svanoort/gerrit-workflow-demo#4]
The Geritt Trigger website at https://wiki.jenkins-ci.org/display/JENKINS/Gerrit+Trigger
  says "Currently the Gerrit trigger does not work anymore with Jenkins 1.651.2 or 2.3 and later."

**Comment by svanoort** [comment]
@wilsonmar Yes, it will still work because the demo is hardcoded to build the Jenkins instance with Jenkins 1.609.x - although if we wanted to update it, we could use the workaround for the SECURITY-170 issue.
